# ─────────────────────────────────────────────────────────────────────────────
# Author   : Frandy Slueue
# Title    : Software Engineering · DevOps Security · IT Ops
# Portfolio: https://frandycode.dev
# GitHub   : https://github.com/frandycode
# Email    : frandyslueue@gmail.com
# Location : Tulsa, OK & Dallas, TX (Central Time)
# Project  : DriveReady — AI-Powered Multi-State Driver Education Platform
# ─────────────────────────────────────────────────────────────────────────────

"""add_battle_room_code_timer

Revision ID: fbc654a77ba3
Revises: e8fd6b501992
Create Date: 2026-03-14 05:31:41.474785

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fbc654a77ba3'
down_revision: Union[str, None] = 'e8fd6b501992'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('battles', sa.Column('room_code', sa.String(length=6), nullable=True))
    op.add_column('battles', sa.Column('timer_seconds', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_battles_room_code'), 'battles', ['room_code'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_battles_room_code'), table_name='battles')
    op.drop_column('battles', 'timer_seconds')
    op.drop_column('battles', 'room_code')
    # ### end Alembic commands ###
